enum AccountType { activo, pasivo, patrimonio, ingreso, gasto, costo }

enum AccountNature { deudora, acreedora }

class ChartOfAccountModel {
  final String id;
  final String code;
  final String name;
  final AccountType type;
  final AccountNature nature;
  final String? parentId;
  final bool isLeaf;
  final double balance;
  final bool isActive;
  final String? description;

  ChartOfAccountModel({
    required this.id,
    required this.code,
    required this.name,
    required this.type,
    required this.nature,
    this.parentId,
    this.isLeaf = true,
    this.balance = 0.0,
    this.isActive = true,
    this.description,
  });

  Map<String, dynamic> toMap() {
    return {
      'code': code,
      'name': name,
      'type': type.name,
      'nature': nature.name,
      'parentId': parentId,
      'isLeaf': isLeaf,
      'balance': balance,
      'isActive': isActive,
      'description': description,
    };
  }

  factory ChartOfAccountModel.fromMap(Map<String, dynamic> map, String docId) {
    return ChartOfAccountModel(
      id: docId,
      code: map['code'] ?? '',
      name: map['name'] ?? '',
      type: AccountType.values.byName(map['type'] ?? 'activo'),
      nature: AccountNature.values.byName(map['nature'] ?? 'deudora'),
      parentId: map['parentId'],
      isLeaf: map['isLeaf'] ?? true,
      balance: (map['balance'] as num?)?.toDouble() ?? 0.0,
      isActive: map['isActive'] ?? true,
      description: map['description'],
    );
  }

  static List<ChartOfAccountModel> defaults() {
    final raw = [
      ChartOfAccountModel(
        id: '',
        code: '1',
        name: 'ACTIVO',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1',
        name: 'Activo Corriente',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1.01',
        name: 'Efectivo y Equivalentes',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1.01.01',
        name: 'Caja General',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.01',
        description: 'Caja General',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.01.02',
        name: 'Caja Chica',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.01',
        description: 'Caja Chica',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.01.03',
        name: 'Bancos - Cuenta Corriente',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.01',
        description: 'Bancos - Cuenta Corriente',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.01.04',
        name: 'Bancos - Cuenta de Ahorros',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.01',
        description: 'Bancos - Cuenta de Ahorros',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.01.05',
        name: 'Dep�sitos a Plazo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.01',
        description: 'Dep�sitos a Plazo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.02',
        name: 'Cuentas por Cobrar',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1.02.01',
        name: 'Clientes - Facturas',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.02',
        description: 'Clientes - Facturas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.02.02',
        name: 'Clientes - Servicios T�cnicos',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.02',
        description: 'Clientes - Servicios T�cnicos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.02.03',
        name: 'Clientes - Venta de Equipos',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.02',
        description: 'Clientes - Venta de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.02.04',
        name: 'Clientes - Venta de Software/Licencias',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.02',
        description: 'Clientes - Venta de Software/Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.02.05',
        name: 'Otras Cuentas por Cobrar',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.02',
        description: 'Otras Cuentas por Cobrar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.03',
        name: 'Inventarios',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1.03.01',
        name: 'Inventario de Equipos',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.03',
        description: 'Inventario de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.03.02',
        name: 'Inventario de Partes y Piezas',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.03',
        description: 'Inventario de Partes y Piezas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.03.03',
        name: 'Inventario de Accesorios',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.03',
        description: 'Inventario de Accesorios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.03.04',
        name: 'Inventario de Software y Licencias',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.03',
        description: 'Inventario de Software y Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.03.05',
        name: 'Inventario de Insumos T�cnicos',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.03',
        description: 'Inventario de Insumos T�cnicos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.04',
        name: 'IVA Cr�dito Tributario (*) [Referencia]',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1',
        description: 'IVA Cr�dito Tributario (*) [Referencia]',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.05',
        name: 'Anticipos y Otros Activos Corrientes',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.1.05.01',
        name: 'Anticipo a Proveedores',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.05',
        description: 'Anticipo a Proveedores',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.05.02',
        name: 'Anticipo al Personal',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.05',
        description: 'Anticipo al Personal',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.05.03',
        name: 'Pr�stamos entre Socios',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.05',
        description: 'Pr�stamos entre Socios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.1.05.04',
        name: 'Otros Deudores',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.1.05',
        description: 'Otros Deudores',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2',
        name: 'Activo No Corriente',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.2.01',
        name: 'Propiedad, Planta y Equipo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.01',
        name: 'Mobiliario y Equipo de Oficina',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Mobiliario y Equipo de Oficina',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.02',
        name: 'Equipo de C�mputo Administrativo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Equipo de C�mputo Administrativo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.03',
        name: 'Herramientas T�cnicas',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Herramientas T�cnicas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.04',
        name: 'Equipo de Diagn�stico',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Equipo de Diagn�stico',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.05',
        name: 'Veh�culo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Veh�culo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.01.06',
        name: 'Software y Licencias de Uso Interno',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.01',
        description: 'Software y Licencias de Uso Interno',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02',
        name: 'Depreciaci�n Acumulada',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.01',
        name: 'Dep. Acum. Mobiliario y Equipo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Mobiliario y Equipo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.02',
        name: 'Dep. Acum. Equipo de C�mputo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Equipo de C�mputo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.03',
        name: 'Dep. Acum. Herramientas T�cnicas',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Herramientas T�cnicas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.04',
        name: 'Dep. Acum. Equipo de Diagn�stico',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Equipo de Diagn�stico',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.05',
        name: 'Dep. Acum. Veh�culo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Veh�culo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.02.06',
        name: 'Dep. Acum. Software y Licencias',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.02',
        description: 'Dep. Acum. Software y Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.03',
        name: 'Activos Intangibles',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '1.2.03.01',
        name: 'Marca y Nombre Comercial',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.03',
        description: 'Marca y Nombre Comercial',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.03.02',
        name: 'Patentes y Derechos de Autor',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.03',
        description: 'Patentes y Derechos de Autor',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.03.03',
        name: 'Llave de Negocio (Goodwill)',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2.03',
        description: 'Llave de Negocio (Goodwill)',
      ),
      ChartOfAccountModel(
        id: '',
        code: '1.2.04',
        name: 'Inversiones a Largo Plazo',
        type: AccountType.activo,
        nature: AccountNature.deudora,
        parentId: '1.2',
        description: 'Inversiones a Largo Plazo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2',
        name: 'PASIVO',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1',
        name: 'Pasivo Corriente',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.01',
        name: 'Cuentas por Pagar - Proveedores',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.01',
        name: 'Proveedores de Equipos',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Proveedores de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.02',
        name: 'Proveedores de Partes y Piezas',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Proveedores de Partes y Piezas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.03',
        name: 'Proveedores de Accesorios',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Proveedores de Accesorios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.04',
        name: 'Proveedores de Software/Licencias',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Proveedores de Software/Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.05',
        name: 'Proveedores de Insumos',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Proveedores de Insumos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.01.06',
        name: 'Otras Cuentas por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.01',
        description: 'Otras Cuentas por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.02',
        name: 'IVA D�bito Fiscal (*) [Referencia]',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        description: 'IVA D�bito Fiscal (*) [Referencia]',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.03',
        name: 'Obligaciones Tributarias',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.03.01',
        name: 'Impuesto a la Renta por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.03',
        description: 'Impuesto a la Renta por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.03.02',
        name: 'Retenciones en la Fuente',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.03',
        description: 'Retenciones en la Fuente',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.03.03',
        name: 'Multas y Sanciones Tributarias',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.03',
        description: 'Multas y Sanciones Tributarias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.03.04',
        name: 'Otros Impuestos por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.03',
        description: 'Otros Impuestos por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04',
        name: 'Obligaciones con el Personal',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.01',
        name: 'Sueldos por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Sueldos por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.02',
        name: 'D�cimo Tercer Sueldo por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'D�cimo Tercer Sueldo por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.03',
        name: 'D�cimo Cuarto Sueldo por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'D�cimo Cuarto Sueldo por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.04',
        name: 'Fondos de Reserva por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Fondos de Reserva por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.05',
        name: 'Aporte Personal IESS por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Aporte Personal IESS por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.06',
        name: 'Aporte Patronal IESS por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Aporte Patronal IESS por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.07',
        name: 'Vacaciones por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Vacaciones por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.04.08',
        name: 'Indemnizaciones por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.04',
        description: 'Indemnizaciones por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.05',
        name: 'Anticipo de Clientes',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        description: 'Anticipo de Clientes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.06',
        name: 'Obligaciones Financieras a Corto Plazo',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.06.01',
        name: 'Pr�stamos Bancarios CP',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.06',
        description: 'Pr�stamos Bancarios CP',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.06.02',
        name: 'Sobregiro Bancario',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.06',
        description: 'Sobregiro Bancario',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.06.03',
        name: 'Tarjeta de Cr�dito Empresarial',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.06',
        description: 'Tarjeta de Cr�dito Empresarial',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.07',
        name: 'Otras Cuentas por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.1.07.01',
        name: 'Pr�stamos de Socios',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.07',
        description: 'Pr�stamos de Socios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.07.02',
        name: 'Honorarios Profesionales por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.07',
        description: 'Honorarios Profesionales por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.07.03',
        name: 'Gastos de Representaci�n por Pagar',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.07',
        description: 'Gastos de Representaci�n por Pagar',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.1.07.04',
        name: 'Otras Obligaciones a Corto Plazo',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.1.07',
        description: 'Otras Obligaciones a Corto Plazo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.2',
        name: 'Pasivo No Corriente',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '2.2.01',
        name: 'Pr�stamos Bancarios a Largo Plazo',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.2',
        description: 'Pr�stamos Bancarios a Largo Plazo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.2.02',
        name: 'Obligaciones por Bonos o T�tulos',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.2',
        description: 'Obligaciones por Bonos o T�tulos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.2.03',
        name: 'Obligaciones por Leasing',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.2',
        description: 'Obligaciones por Leasing',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.2.04',
        name: 'Provisiones para Jubilaci�n',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.2',
        description: 'Provisiones para Jubilaci�n',
      ),
      ChartOfAccountModel(
        id: '',
        code: '2.2.05',
        name: 'Otras Obligaciones a Largo Plazo',
        type: AccountType.pasivo,
        nature: AccountNature.acreedora,
        parentId: '2.2',
        description: 'Otras Obligaciones a Largo Plazo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3',
        name: 'PATRIMONIO',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '3.1',
        name: 'Capital',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '3.1.01',
        name: 'Capital Social',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1',
        description: 'Capital Social',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.1.02',
        name: 'Aportes Pendientes de Capitalizaci�n',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1',
        description: 'Aportes Pendientes de Capitalizaci�n',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.1.03',
        name: 'Reservas',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '3.1.03.01',
        name: 'Reserva Legal',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1.03',
        description: 'Reserva Legal',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.1.03.02',
        name: 'Reserva Estatutaria',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1.03',
        description: 'Reserva Estatutaria',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.1.03.03',
        name: 'Reserva Facultativa',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.1.03',
        description: 'Reserva Facultativa',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.2',
        name: 'Resultados',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '3.2.01',
        name: 'Utilidad del Ejercicio',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.2',
        description: 'Utilidad del Ejercicio',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.2.02',
        name: 'P�rdida del Ejercicio',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.2',
        description: 'P�rdida del Ejercicio',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.2.03',
        name: 'Utilidades Acumuladas',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.2',
        description: 'Utilidades Acumuladas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.2.04',
        name: 'P�rdidas Acumuladas',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.2',
        description: 'P�rdidas Acumuladas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.2.05',
        name: 'Resultado del Ejercicio Anterior',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.2',
        description: 'Resultado del Ejercicio Anterior',
      ),
      ChartOfAccountModel(
        id: '',
        code: '3.3',
        name: 'Super�vit por Revalorizaci�n',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '3.3.01',
        name: 'Super�vit por Revalorizaci�n de Activos Fijos',
        type: AccountType.patrimonio,
        nature: AccountNature.acreedora,
        parentId: '3.3',
        description: 'Super�vit por Revalorizaci�n de Activos Fijos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4',
        name: 'INGRESOS',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.1',
        name: 'Ventas de Productos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.1.01',
        name: 'Venta de Equipos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.1.01.01',
        name: 'Venta de Computadoras y Laptops',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.01',
        description: 'Venta de Computadoras y Laptops',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.01.02',
        name: 'Venta de Servidores',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.01',
        description: 'Venta de Servidores',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.01.03',
        name: 'Venta de Otros Equipos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.01',
        description: 'Venta de Otros Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.02',
        name: 'Venta de Partes y Piezas',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.1.02.01',
        name: 'Venta de Componentes Internos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.02',
        description: 'Venta de Componentes Internos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.02.02',
        name: 'Venta de Perif�ricos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.02',
        description: 'Venta de Perif�ricos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.02.03',
        name: 'Venta de Otros Componentes',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.02',
        description: 'Venta de Otros Componentes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.03',
        name: 'Venta de Software y Licencias',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.1.03.01',
        name: 'Venta de Licencias Originales',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.03',
        description: 'Venta de Licencias Originales',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.03.02',
        name: 'Venta de Software a Medida',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.03',
        description: 'Venta de Software a Medida',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.03.03',
        name: 'Venta de Suscripciones y Renovaciones',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.03',
        description: 'Venta de Suscripciones y Renovaciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.1.03.04',
        name: 'Venta de Accesorios de Software',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.1.03',
        description: 'Venta de Accesorios de Software',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2',
        name: 'Servicios T�cnicos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.01',
        name: 'Servicio de Reparaci�n',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.01.01',
        name: 'Reparaci�n de Laptops',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.01',
        description: 'Reparaci�n de Laptops',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.01.02',
        name: 'Reparaci�n de Computadoras de Escritorio',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.01',
        description: 'Reparaci�n de Computadoras de Escritorio',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.01.03',
        name: 'Reparaci�n de Impresoras',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.01',
        description: 'Reparaci�n de Impresoras',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.01.04',
        name: 'Reparaci�n de Otros Equipos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.01',
        description: 'Reparaci�n de Otros Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.02',
        name: 'Mantenimiento Preventivo',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.02.01',
        name: 'Limpieza y Mantenimiento de Equipos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.02',
        description: 'Limpieza y Mantenimiento de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.02.02',
        name: 'Mantenimiento de Impresoras',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.02',
        description: 'Mantenimiento de Impresoras',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.03',
        name: 'Instalaci�n y Configuraci�n',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.03.01',
        name: 'Instalaci�n de Sistemas Operativos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.03',
        description: 'Instalaci�n de Sistemas Operativos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.03.02',
        name: 'Instalaci�n de Software y Paquetes',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.03',
        description: 'Instalaci�n de Software y Paquetes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.03.03',
        name: 'Configuraci�n de Redes',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.03',
        description: 'Configuraci�n de Redes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.03.04',
        name: 'Configuraci�n de Correo y Nube',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.03',
        description: 'Configuraci�n de Correo y Nube',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.04',
        name: 'Soporte T�cnico',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.04.01',
        name: 'Soporte Remoto',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.04',
        description: 'Soporte Remoto',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.04.02',
        name: 'Soporte Presencial',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.04',
        description: 'Soporte Presencial',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.04.03',
        name: 'Consultor�a T�cnica',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.04',
        description: 'Consultor�a T�cnica',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.05',
        name: 'Recuperaci�n de Datos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.2.05.01',
        name: 'Recuperaci�n de Discos Duros',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.05',
        description: 'Recuperaci�n de Discos Duros',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.05.02',
        name: 'Recuperaci�n de Memorias USB',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.05',
        description: 'Recuperaci�n de Memorias USB',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.05.03',
        name: 'Recuperaci�n de Otros Dispositivos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2.05',
        description: 'Recuperaci�n de Otros Dispositivos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.2.06',
        name: 'Garant�as y Servicios Postventa',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.2',
        description: 'Garant�as y Servicios Postventa',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3',
        name: 'Otros Ingresos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '4.3.01',
        name: 'Ingresos Financieros',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Ingresos Financieros',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3.02',
        name: 'Descuentos Obtenidos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Descuentos Obtenidos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3.03',
        name: 'Ingresos por Alquiler de Equipos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Ingresos por Alquiler de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3.04',
        name: 'Venta de Activos Fijos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Venta de Activos Fijos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3.05',
        name: 'Indemnizaciones y Cobros Extraordinarios',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Indemnizaciones y Cobros Extraordinarios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '4.3.06',
        name: 'Otros Ingresos Operativos',
        type: AccountType.ingreso,
        nature: AccountNature.acreedora,
        parentId: '4.3',
        description: 'Otros Ingresos Operativos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5',
        name: 'GASTOS OPERATIVOS',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.1',
        name: 'Gastos de Personal',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.1.01',
        name: 'Sueldos y Salarios',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Sueldos y Salarios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.02',
        name: 'Horas Extras',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Horas Extras',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.03',
        name: 'Comisiones sobre Ventas',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Comisiones sobre Ventas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.04',
        name: 'D�cimo Tercer Sueldo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'D�cimo Tercer Sueldo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.05',
        name: 'D�cimo Cuarto Sueldo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'D�cimo Cuarto Sueldo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.06',
        name: 'Fondos de Reserva',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Fondos de Reserva',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.07',
        name: 'Aporte Patronal IESS',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Aporte Patronal IESS',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.08',
        name: 'Vacaciones',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Vacaciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.09',
        name: 'Indemnizaciones',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Indemnizaciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.10',
        name: 'Beneficios Adicionales',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Beneficios Adicionales',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.1.11',
        name: 'Seguro M�dico Particular',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.1',
        description: 'Seguro M�dico Particular',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2',
        name: 'Gastos de Operaci�n del Local',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.2.01',
        name: 'Arriendo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.2.01.01',
        name: 'Arriendo de Local Comercial',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.01',
        description: 'Arriendo de Local Comercial',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.01.02',
        name: 'Arriendo de Equipos',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.01',
        description: 'Arriendo de Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.02',
        name: 'Servicios B�sicos',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.2.02.01',
        name: 'Electricidad',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.02',
        description: 'Electricidad',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.02.02',
        name: 'Agua Potable',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.02',
        description: 'Agua Potable',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.02.03',
        name: 'Internet y Telefon�a',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.02',
        description: 'Internet y Telefon�a',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.02.04',
        name: 'Televisi�n por Cable',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.02',
        description: 'Televisi�n por Cable',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.03',
        name: 'Suministros de Oficina y Taller',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.2.03.01',
        name: 'Material de Oficina',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.03',
        description: 'Material de Oficina',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.03.02',
        name: 'Insumos de Taller',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.03',
        description: 'Insumos de Taller',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.03.03',
        name: 'Insumos de Limpieza',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.03',
        description: 'Insumos de Limpieza',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.03.04',
        name: 'Insumos de Seguridad',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2.03',
        description: 'Insumos de Seguridad',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.04',
        name: 'Seguros',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2',
        description: 'Seguros',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.2.05',
        name: 'Mantenimiento del Local',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.2',
        description: 'Mantenimiento del Local',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.3',
        name: 'Gastos de Veh�culo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.3.01',
        name: 'Combustible y Lubricantes',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.3',
        description: 'Combustible y Lubricantes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.3.02',
        name: 'Mantenimiento Vehicular',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.3',
        description: 'Mantenimiento Vehicular',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.3.03',
        name: 'Matr�cula y Revisi�n Vehicular',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.3',
        description: 'Matr�cula y Revisi�n Vehicular',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.3.04',
        name: 'Seguro Vehicular',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.3',
        description: 'Seguro Vehicular',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.3.05',
        name: 'Peajes y Estacionamientos',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.3',
        description: 'Peajes y Estacionamientos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4',
        name: 'Gastos de Marketing y Ventas',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.4.01',
        name: 'Publicidad y Marketing Digital',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Publicidad y Marketing Digital',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.02',
        name: 'Marketing con Influencers',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Marketing con Influencers',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.03',
        name: 'Material Publicitario F�sico',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Material Publicitario F�sico',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.04',
        name: 'Comisiones por Tarjetas',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Comisiones por Tarjetas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.05',
        name: 'Transporte y Delivery',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Transporte y Delivery',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.06',
        name: 'Promociones y Descuentos',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Promociones y Descuentos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.4.07',
        name: 'Garant�as y Devoluciones',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.4',
        description: 'Garant�as y Devoluciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.5',
        name: 'Gastos Financieros',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.5.01',
        name: 'Comisiones Bancarias',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.5',
        description: 'Comisiones Bancarias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.5.02',
        name: 'Intereses por Pr�stamos',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.5',
        description: 'Intereses por Pr�stamos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.5.03',
        name: 'Intereses por Sobregiro',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.5',
        description: 'Intereses por Sobregiro',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.5.04',
        name: 'Intereses por Tarjeta de Cr�dito',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.5',
        description: 'Intereses por Tarjeta de Cr�dito',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6',
        name: 'Gastos Tributarios',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.6.01',
        name: 'Impuesto a la Renta',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Impuesto a la Renta',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6.02',
        name: 'Patente Municipal',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Patente Municipal',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6.03',
        name: 'Tasa de Funcionamiento (Bomberos)',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Tasa de Funcionamiento (Bomberos)',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6.04',
        name: 'Permisos y Licencias',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Permisos y Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6.05',
        name: 'Multas y Sanciones',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Multas y Sanciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.6.06',
        name: 'Otros Impuestos y Tasas',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.6',
        description: 'Otros Impuestos y Tasas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7',
        name: 'Depreciaci�n y Amortizaci�n',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.7.01',
        name: 'Depreciaci�n Mobiliario y Equipo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Depreciaci�n Mobiliario y Equipo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.02',
        name: 'Depreciaci�n Equipo de C�mputo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Depreciaci�n Equipo de C�mputo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.03',
        name: 'Depreciaci�n Herramientas T�cnicas',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Depreciaci�n Herramientas T�cnicas',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.04',
        name: 'Depreciaci�n Equipo de Diagn�stico',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Depreciaci�n Equipo de Diagn�stico',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.05',
        name: 'Depreciaci�n Veh�culo',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Depreciaci�n Veh�culo',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.06',
        name: 'Amortizaci�n de Software y Licencias',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Amortizaci�n de Software y Licencias',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.7.07',
        name: 'Amortizaci�n de Marca y Patentes',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.7',
        description: 'Amortizaci�n de Marca y Patentes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.8',
        name: 'Servicios Profesionales',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.8.01',
        name: 'Honorarios Contador',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.8',
        description: 'Honorarios Contador',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.8.02',
        name: 'Honorarios Abogado',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.8',
        description: 'Honorarios Abogado',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.8.03',
        name: 'Servicios de Consultor�a',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.8',
        description: 'Servicios de Consultor�a',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.8.04',
        name: 'Servicios de Tecnolog�a',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.8',
        description: 'Servicios de Tecnolog�a',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9',
        name: 'Gastos Varios',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '5.9.01',
        name: 'Gastos de Representaci�n',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'Gastos de Representaci�n',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9.02',
        name: 'Vi�ticos y Movilizaci�n',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'Vi�ticos y Movilizaci�n',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9.03',
        name: 'P�rdida en Baja de Inventario',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'P�rdida en Baja de Inventario',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9.04',
        name: 'P�rdida por Incobrabilidad',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'P�rdida por Incobrabilidad',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9.05',
        name: 'Donaciones',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'Donaciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '5.9.06',
        name: 'Gastos Generales',
        type: AccountType.gasto,
        nature: AccountNature.deudora,
        parentId: '5.9',
        description: 'Gastos Generales',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6',
        name: 'COSTOS DE VENTAS',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.1',
        name: 'Costo de Mercader�a Vendida (CMV)',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.1.01',
        name: 'Costo de Venta - Equipos',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.1.01.01',
        name: 'CMV Computadoras y Laptops',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.01',
        description: 'CMV Computadoras y Laptops',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.01.02',
        name: 'CMV Servidores',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.01',
        description: 'CMV Servidores',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.01.03',
        name: 'CMV Otros Equipos',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.01',
        description: 'CMV Otros Equipos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.02',
        name: 'Costo de Venta - Partes y Piezas',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.1.02.01',
        name: 'CMV Componentes Internos',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.02',
        description: 'CMV Componentes Internos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.02.02',
        name: 'CMV Perif�ricos',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.02',
        description: 'CMV Perif�ricos',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.02.03',
        name: 'CMV Otros Componentes',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.02',
        description: 'CMV Otros Componentes',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.03',
        name: 'Costo de Venta - Software y Licencias',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.1.03.01',
        name: 'CMV Licencias Originales',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.03',
        description: 'CMV Licencias Originales',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.03.02',
        name: 'CMV Software a Medida',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.03',
        description: 'CMV Software a Medida',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.03.03',
        name: 'CMV Suscripciones',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1.03',
        description: 'CMV Suscripciones',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.1.04',
        name: 'Costo de Venta - Accesorios',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.1',
        description: 'Costo de Venta - Accesorios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2',
        name: 'Costo de Servicios T�cnicos Prestados',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.2.01',
        name: 'Repuestos Utilizados en Servicios',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.2.01.01',
        name: 'Repuestos de Reparaci�n Laptops',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2.01',
        description: 'Repuestos de Reparaci�n Laptops',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2.01.02',
        name: 'Repuestos de Reparaci�n PCs',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2.01',
        description: 'Repuestos de Reparaci�n PCs',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2.01.03',
        name: 'Repuestos de Impresoras',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2.01',
        description: 'Repuestos de Impresoras',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2.02',
        name: 'Mano de Obra T�cnica Tercerizada',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2',
        description: 'Mano de Obra T�cnica Tercerizada',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2.03',
        name: 'Insumos Consumidos en Servicios',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2',
        description: 'Insumos Consumidos en Servicios',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.2.04',
        name: 'Costos de Laboratorio/Taller',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.2',
        description: 'Costos de Laboratorio/Taller',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.3',
        name: 'Variaciones de Inventario',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6',
        isLeaf: false,
      ), // grupo
      ChartOfAccountModel(
        id: '',
        code: '6.3.01',
        name: 'P�rdida por Merma de Inventario',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.3',
        description: 'P�rdida por Merma de Inventario',
      ),
      ChartOfAccountModel(
        id: '',
        code: '6.3.02',
        name: 'Provisi�n por Obsolescencia',
        type: AccountType.costo,
        nature: AccountNature.deudora,
        parentId: '6.3',
        description: 'Provisi�n por Obsolescencia',
      ),
    ];

    // Asignar un ID legible a cada cuenta seg�n su tipo y c�digo:
    //   Activo=A, Pasivo=P, Patrimonio=PAT, Ingreso=I, Gasto=G, Costo=C
    return raw.map((a) => a.copyWith(id: buildId(a.type, a.code))).toList();
  }

  /// Genera un ID legible a partir del tipo y c�digo de la cuenta.
  /// Ejemplos: A-1.1.01.01 (Caja), P-2.1.01.01 (Proveedores), PAT-3.1.01 (Capital),
  ///           I-4.1.01.01 (Venta), G-5.1.01 (Sueldos), C-6.1.01.01 (CMV).
  static String buildId(AccountType type, String code) {
    final prefix = switch (type) {
      AccountType.activo => 'A',
      AccountType.pasivo => 'P',
      AccountType.patrimonio => 'PAT',
      AccountType.ingreso => 'I',
      AccountType.gasto => 'G',
      AccountType.costo => 'C',
    };
    return '$prefix-$code';
  }

  ChartOfAccountModel copyWith({
    String? id,
    String? code,
    String? name,
    AccountType? type,
    AccountNature? nature,
    String? parentId,
    bool? isLeaf,
    double? balance,
    bool? isActive,
    String? description,
  }) {
    return ChartOfAccountModel(
      id: id ?? this.id,
      code: code ?? this.code,
      name: name ?? this.name,
      type: type ?? this.type,
      nature: nature ?? this.nature,
      parentId: parentId ?? this.parentId,
      isLeaf: isLeaf ?? this.isLeaf,
      balance: balance ?? this.balance,
      isActive: isActive ?? this.isActive,
      description: description ?? this.description,
    );
  }
}
